{"para_infantry_ger"
	("squad_vehicle5" period(late) year(late) year(late) cd(90) ci(180) t(vehicle) side(ger) vehicle(ju-52) crew1(pilot:2) crew2(fallsch_rifle:4) crew3(fallsch_sa:4) crew4(fallsch_mg:1) crew5(fallsch_mg_asst:1) g(lightc) b(squad) )
	{tags "limit2"}
}
{"88mm_raketenwerfer"
	("vehicle" period(late) year(late) year(late) cd(0) ci(30) t(cannon) side(ger) crew(artilleryman:3) g(empl2) b(support) cw(0) cp(6)
	cost(240))
}
{"128mm_pak44"
	("vehicle"  period(late) year(late) year(late) cd(0) ci(30) t(heavycan) side(ger) crew(artilleryman:5) g(empl2) b(support) cw(2) cp(35)
	cost(800))
}
{"panzer2j"
	("vehicle2" period(late) year(late) year(late) cd(90) ci(60) t(light) side(ger) crew1(tankman:2) crew2(tank_commander:1) g(light2) b(lt) cw(4) cp(15)
	cost(300))
}
{"sdkfz251d_2"
	("vehicle2"  period(late) year(late) year(late) cd(60) ci(30) t(vehicle) side(ger) crew1(rifleman_1:1) crew2(artilleryman:3) g(wheel10) b(lt) cw(2) cp(13)
	cost(280))
}
{"stug4g"
	("vehicle2" period(late) year(late) year(late) cd(360) ci(60) t(medium) side(ger) crew1(tankman_stug:3) crew2(tank_commander_stug:1) g(spg2) b(td) cw(6) cp(25)
	cost(600))
}
{"pz5g_m10"
	("vehicle2" period(late) year(late) year(late) cd(480) ci(60) t(medium) side(ger) crew1(tankman:4) crew2(tank_commander:1) g(heavy1) b(mt) cw(6) cp(30)
	cost(1150)) 
}
{"88mmflak37sfl"
	("vehicle2" period(late) year(late) year(late) cd(600) ci(180) t(vehicle ) side(ger) crew1(tankman_stug:3) crew2(tank_commander_stug:1) g(spg6) b(td) cw(6) cp(30)
	cost(800)) 
}
{"tiger_p"
	("vehicle2" period(late) year(late) year(late) cd(600) ci(60) t(heavy) side(ger) crew1(tankman:4) crew2(tank_commander:1) g(heavy2) b(ht) cw(8) cp(35)
	cost(1280))
}
{"zgkw303f"
	("vehicle2" period(late) year(late) year(late) cd(600) ci(180) t(light heavyart) side(ger) crew1(tankman:1) crew2(tank_commander:1) g(spg4) b(art) cw(4) cp(20)
	cost(1100))
}
{"panzer5g_steelrims"
	("vehicle2" period(late) year(late) year(late) cd(720) ci(60) t(medium) side(ger) crew1(tankman:4) crew2(tank_commander:1) g(heavy1) b(ht) cw(6) cp(30)
	cost(1200)) 
}
{"tiger1e_early"
	("vehicle2" period(late) year(late) year(late) cd(720) ci(60) t(heavy) side(ger) crew1(tankman:4) crew2(tank_commander:1) g(heavy2) b(ht) cw(8) cp(30)
	cost(1280)) 
}
{"ju-52"
	("vehicle"  period(late) year(late) year(late) cd(0) ci(0) t(doctrineonly doc_only ita hun fin) side(usaf) crew(pilot:4) g(spg8) b(doctrine) cw(0) cp(11)
	cost(120))
}
