{"para_infantry_fin"
	("squad_vehicle5" period(late) year(late) cd(90) ci(180) t(vehicle) side(fin) vehicle(ju-52) crew1(pilot:2) crew2(elite_rifle:4) crew3(elite_smg_stick:4) crew4(elite_mg:1) crew5(elite_mg_asst:1) g(lightc) b(squad) )
	{tags "limit2"}
}
{"25mm_pstk34"
	("vehicle"  period(late) year(late) cd(0) ci(10) t(cannon) side(fin) crew(artilleryman:2) g(empl6) b(support) cw(1) cp(5)
	cost(200))
}
{"105mm_k29"
	("vehicle"  period(late) year(late) cd(900) ci(30) t(artillery) side(fin) crew(artilleryman:4) g(empl24) b(art) cw(1) cp(35)
	cost(850))
}
{"210mm_h17"
	("vehicle"  period(late) year(late) cd(1200) ci(30) t(heavyart artillery) side(fin) crew(artilleryman:4) g(empl30) b(art) cw(1) cp(45)
	cost(1200))
}
{"vickers_6t_b"
	("vehicle2" period(late) year(late) cd(90) ci(60) t(light) side(fin) crew1(tankman:3) crew2(tank_commander:1) g(light4) b(lt) cw(4) cp(12)
	cost(240))
}
{"t3476_42_fin"
	("vehicle2" period(late) year(late) cd(480) ci(60) t(medium) side(fin) crew1(tankman:3) crew2(tank_commander:1) g(medium1) b(mt) cw(6) cp(21)
	cost(400))
}
{"t3485_fin"
	("vehicle2" period(late) year(late) cd(480) ci(60) t(medium) side(fin) crew1(tankman:4) crew2(tank_commander:1) g(medium3) b(mt) cw(6) cp(25)
	cost(700))
}
{"po2_fin"
	("vehicle"  period(late) year(late) cd(0) ci(0) t(doctrineonly doc_only) side(fin) crew(pilot:2) g(spg8) b(doctrine) cw(0) cp(11)
	cost(500))
}
{"fokker_fin"
	("vehicle"  period(late) year(late) cd(90) ci(30) t(doctrineonly doc_only) side(fin) crew(pilot:1) g(spg9) b(lt) cw(0) cp(25)
	cost(200))
}
