{"para_infantry_rus"
	("squad_vehicle5" period(late) year(late) cd(90) ci(180) t(vehicle) side(rus) vehicle(li-2) crew1(pilot:2) crew2(para_rfl:4) crew3(para_smg:4) crew4(para_mg:1) crew5(para_mg_asst:1) g(lightc) b(squad) )
	{tags "limit2"}
}
{"m3_rus"
	("vehicle"  period(late) year(late) cd(0) ci(30) t(vehicle) side(rus) crew(rifleman_1:2) g(wheel10) b(supply) cw(2) cp(8)
	cost(180))
}
{"m17"
	("vehicle2" period(late) year(late) cd(90) ci(30) t(vehicle) side(rus) crew1(rifleman_1:2) crew2(tank_commander:1) g(wheel11) b(lt) cw(2) cp(8)
	cost(200))
}
{"zis6_61k"
	("vehicle"  period(late) year(late) cd(90) ci(60) t(vehicle) side(rus) crew(artilleryman:4) g(wheel7) b(lt) cw(2) cp(8)
	cost(250))
}
{"t80"
	("vehicle2" period(late) year(late) cd(90) ci(60) t(light) side(rus) crew1(tankman:1) crew2(tank_commander:1) g(light3) b(lt) cw(4) cp(15)
	cost(320))
}
{"su57"
	("vehicle2" period(late) year(late) cd(90) ci(30) t(light) side(rus) crew1(tankman:3) crew2(tank_commander:1) g(spg2) b(lt) cw(4) cp(20)
	cost(450))
}
{"t3485_43"
	("vehicle2" period(late) year(late) cd(360) ci(60) t(medium) side(rus) crew1(tankman:4) crew2(tank_commander:1) g(medium3) b(mt) cw(6) cp(24)
	cost(640)) 
}
{"wolverine"
	("vehicle2" period(late) year(late) cd(600) ci(60) t(medium) side(rus) crew1(tankman:4) crew2(tank_commander:1) g(medium3) b(td) cw(6) cp(25)
	cost(710))
}
{"152mm_d1"
	("vehicle"  period(late) year(late) cd(1200) ci(30) t(heavyart artillery) side(rus) crew(artilleryman:5) g(empl12) b(art) cw(1) cp(30)
	cost(1000))
}
{"kv122"
	("vehicle2" period(late) year(late) cd(720) ci(60) t(heavy) side(rus) crew1(tankman:4) crew2(tank_commander:1) g(heavy1) b(ht) cw(8) cp(30)
	cost(1020)) 
}
{"bm8-48"
	("vehicle"  period(late) year(late) cd(120) ci(30) t(heavyart artillery vehicle) side(rus) crew(tankman:2) g(wheel5) b(art) cw(2) cp(33)
	cost(1100))
}
{"isu122"
	("vehicle2" period(late) year(late) cd(600) ci(60) t(heavy) side(rus) crew1(tankman:4) crew2(tank_commander:1) g(spg7) b(td) cw(8) cp(30)
	cost(1200)) 
}
{"li-2"
	("vehicle"  period(late) year(late) cd(0) ci(0) t(doctrineonly doc_only) side(rus) crew(pilot:1) g(spg8) b(doctrine) cw(0) cp(11)
	cost(100))
}