	{"t3_hmc"
		{vehicle_view "t3_hmc"}
	}
	{"t1_hmc"
		{vehicle_view "t1_hmc"}
	}	
	{"mtls_1g14"
		{vehicle_view "mtls_1g14"}
	}	
	{"m1_combat_car"
		{vehicle_view "m1_combat_car"}
	}	
	{"m2a1"
		{vehicle_view "m2a1"}
	}	
	{"m2a4"
		{vehicle_view "m2a4"}
	}	
	{"t1e1"
		{vehicle_view "t1e1"}
	}	
	{"t1e3"
		{vehicle_view "t1e1"}
	}		
	{"t3476_42_pt3"
		{vehicle_view "t34_76"}
	}
	{"bt7m"
		{vehicle_view "bt7"}
	}
	{"m4a3_75_crab"
		{vehicle_view "m4a3_75_early"}
	}	
	{"churchill3_avre"
		{vehicle_view "churchill3"}
	}
	{"kht27"
		{vehicle_view "t27"}
	}
	{"zis12_94km"
		{vehicle_view "gaz_aa"}
	}
	{"stuh42_late"
		{vehicle_view "stug_h42"}
	}	
	{"t80"
		{vehicle_view "t70"}
	}
	{"t34s"
		{vehicle_view "t34_76"}
	}
	{"t26_32"
		{vehicle_view "t26_31"}
	}
	{"panzer3j_funk"
		{vehicle_view "panzer3e"}
	}
	{"panzer5fg"
		{vehicle_view "panzer5"}
	}
	{"panzer5g_armor"
		{vehicle_view "panzer5"}
	}
	{"panzer5g_fg1250"
		{vehicle_view "panzer5"}
	}
	{"gaz_aaa_72k_early"
		{vehicle_view "gaz_aa"}
	}	
	{"25mm_72k_early"
		{vehicle_view "cannon_25mm_72k"}
	}
	{"sdkfz301b"
		{vehicle_view "pz2f"}
	}
	{"sdkfz301c"
		{vehicle_view "pz2f"}
	}
	{"zis42"
		{vehicle_view "zis5"}
	}
	{"su5_2"
		{vehicle_view "su26"}
	}
	{"sdkfz251c_ru"
		{vehicle_view "sdkfz251c"}
	}
	{"blitz3_6_engineering_e"
		{vehicle_view "car"}
	}
	{"blitz3_6_engineering_m"
		{vehicle_view "car"}
	}
	{"blitz3_6_engineering_l"
		{vehicle_view "car"}
	}
	{"cckw_engineer_m"
		{vehicle_view "cckw_engineer"}
	}
	{"cckw_engineer_late_fl"
		{vehicle_view "cckw_engineer_late"}
	}
	{"zis5eng_e"
		{vehicle_view "zis5"}
	}
	{"zis5eng_m"
		{vehicle_view "zis5"}
	}
	{"zis5eng_l"
		{vehicle_view "zis5"}
	}
	{"zis5eng_ll_l"
		{vehicle_view "zis5"}
	}
	{"zis5eng_ll_m"
		{vehicle_view "zis5"}
	}
	{"us6"
		{vehicle_view "zis5"}
	}
	{"sdkfz10_5"
		{vehicle_view "sdkfz10_4"}
	}
	{"kv1_40_early"
		{vehicle_view "kv1_41"}
	}
	{"76mm_m1902_e"
		{vehicle_view "cannon_76mm_m1902"}
	}
	{"kv8s"
		{vehicle_view "kv1s"}
	}
	{"t3485_43"
		{vehicle_view "t34_85"}
	}
	{"panzer4f1_e"
		{vehicle_view "panzer4f1"}
	}	
	{"kugelblitz"
		{vehicle_view "kugelblitz"}
	}	
	{"ford_gpa_rus"
		{vehicle_view "ford_gpa"}
	}	
	{"stug3e"
		{vehicle_view "stug3b"}
	}
	{"stug4"
		{vehicle_view "stug3g"}
	}
	{"stug4_late"
		{vehicle_view "stug3_late"}
	}
	{"stug4_last"
		{vehicle_view "stug3_late"}
	}
	{"panzer3l_funk"
		{vehicle_view "panzer3l"}
	}
	{"ford_v3000_eng_e"
		{vehicle_view "fordV3000"}
	}
	{"ford_v3000_eng_m"
		{vehicle_view "fordV3000"}
	}
	{"ford_v3000_eng_l"
		{vehicle_view "fordV3000"}
	}
	{"m17_mgmc"
		{vehicle_view "m16_mgmc"}
	}
	{"76mm_m1933_late"
		{vehicle_view "cannon_76mm_m1933"}
	}
	{"t3476_41_pt3"
		{vehicle_view "t3476_41"}
	}
	{"bt7_35"
		{vehicle_view "bt5"}
	}
	{"152mm_h37"
		{vehicle_view "cannon_152mm_ml20"}
	}
	{"panzer4f1_vorpanzer"
		{vehicle_view "panzer4f1"}
	}
	{"kht133"
		{vehicle_view "kht130"}
	}
	{"t3476_40_early"
		{vehicle_view "t3476_40"}
	}
	{"su76i"
		{vehicle_view "stug3f"}
	}
	{"t5"
		{vehicle_view "panzer5"}
	}
	{"isu122"
		{vehicle_view "isu152"}
	}
	{"t34_747"
		{vehicle_view "t34_76"}
	}
	{"sdkfz251c_8"
		{vehicle_view "sdkfz251c"}
	}
	{"t26a"
		{vehicle_view "t26_31"}
	}
	{"t26_33_fin_m"
		{vehicle_view "t26_fin"}
	}
	{"t26c"
		{vehicle_view "t26_fin"}
	}
	{"t26c_m"
		{vehicle_view "t26_fin"}
	}
	{"t26c_39"
		{vehicle_view "t26_fin"}
	}
	{"t26c_39_m"
		{vehicle_view "t26_fin"}
	}
	{"t26c_t130"
		{vehicle_view "t26_fin"}
	}
	{"t26c_t133"
		{vehicle_view "t26_fin"}
	}
	{"su122_sap"
		{vehicle_view "su122"}
	}
	{"su100_early"
		{vehicle_view "su85"}
	}
	{"is2_45_vet"
		{vehicle_view "is1_43"}
	}
	{"panzer5g_vet"
		{vehicle_view "panzer5"}
	}
	{"panzer4_70_v_reserve"
		{vehicle_view "panzer4_70_v"}
	}
	{"fai_bab_b"
		{vehicle_view "ba20"}
	}
	{"ba20_bab_b"
		{vehicle_view "ba20"}
	}
	{"isu152_vet"
		{vehicle_view "isu152"}
	}
	{"m10_gmc_rus"
		{vehicle_view "m10_gmc"}
	}
	{"su57"
		{vehicle_view "m3a1_gmc"}
	}
	{"m26_pershing_eagle7"
		{vehicle_view "m26_pershing"}
	}
	{"panzer4j_late"
		{vehicle_view "panzer4j"}
	}
	{"panzer2_flamm"
		{vehicle_view "panzer2_flamm"}
	}
	{"76mm_f22_ger"
		{vehicle_view "cannon_76mm_f22"}
	}
	{"bedford_oyd_ger"
		{vehicle_view "bedford_oyd"}
	}
	{"ford_v3000_ger"
		{vehicle_view "fordV3000"}
	}
	{"m3a1_commander_rus"
		{vehicle_view "m3a1_commander"}
	}