(define "Type1_MG"
	{link_sound	 		"MG_Mid"		"weapon/shot/mgun/type1hmg_burst/"}
	{link_sound	 		"MG_Far"		"weapon/shot/smallarms/s4/d3/RUS/DShK38/"}
)
(define "Type92_MG"
	{link_sound	 		"MG_Mid"		"weapon/shot/mgun/type92_shot/"}
	{link_sound	 		"MG_Far"		"weapon/shot/smallarms/s3/d3/RUS/DP27/"}
)
(define "Breda38_MG"
	{link_sound	 		"MG_Mid"		"weapon/shot/mgun/breda_37_burst/"}
	{link_sound	 		"MG_Far"		"weapon/shot/smallarms/s3/d3/FIN/LS26/"}
)
(define "Vickers_MG"
	{link_sound	 		"MG_Mid"		"weapon/shot/smallarms/s3/d2/Shared/Maxim_Gun/"}
	{link_sound	 		"MG_Far"		"weapon/shot/smallarms/s3/d3/Shared/Maxim_Gun/"}
)
(define "BESA_MGUN"
	{link_sound	 		"MG_Mid"		"weapon/shot/smallarms/s3/d2/Shared/ZB37/"}
	{link_sound 		"MG_Far"		"weapon/shot/smallarms/s3/d3/Shared/ZB37/"}
)
(define "Gebauer_MG"
	{link_sound 		"SMG_Mid"		"weapon/shot/smallarms/s1/d2/FIN/KP31/"}
	{link_sound 		"SMG_Far"		"weapon/shot/smallarms/s1/d3/FIN/KP31/"}
)
(define "Hotchkiss_MG"
	{link_sound 		"MG_Mid"		"weapon/shot/mgun/hotchkiss_mle_1914_burst/"}
	{link_sound 		"MG_Far"		"weapon/shot/smallarms/s3/d3/USA/M1919A4/"}
)