{"t26_40"
	("vehicle2" period(mid) year(mid) cd(90) ci(60) t(light) side(rus) crew1(tankman:2) crew2(tank_commander:1) g(light1) b(lt) cd2(90) ci2(60) cw(4) cp(12)
	cost(240))
}
{"ba11"
	("vehicle2" period(mid) year(mid) cd(0) ci(60) t(vehicle) side(rus) crew1(tankman:3) crew2(tank_commander:1) g(wheel4) b(lt) cd2(0) ci2(60) cw(2) cp(10)
	cost(270))
}
{"76mm_f22_usv"
	("vehicle"  period(mid) year(mid) cd(240) ci(60) t(cannon mediumcan) side(rus) crew(artilleryman:4) g(empl6) b(support) cd2(240) ci2(60) cw(0) cp(14)
	cost(380))
}
{"su5"
	("vehicle2" period(mid) year(mid) cd(240) ci(60) t(light) side(rus) crew1(tankman:2) crew2(tank_commander:1) g(light8) b(lt) cd2(240) ci2(60) cw(4) cp(15)
	cost(420))
}
{"matilda2"
	("vehicle2" period(mid) year(mid) cd(480) ci(60) t(medium) side(rus) crew1(tankman:3) crew2(tank_commander:1) g(medium3) b(mt) cd2(480) ci2(60) cw(6) cp(20) 
	cost(420))
}
{"t3476_41w"
	("vehicle2" period(mid) year(mid) cd(480) ci(60) t(medium) side(rus) crew1(tankman:3) crew2(tank_commander:1) g(medium4) b(mt) cd2(480) ci2(60) cw(6) cp(22)
	cost(430))
}
{"t3476_uztm"
	("vehicle2" period(mid) year(mid) cd(480) ci(60) t(medium) side(rus) crew1(tankman:3) crew2(tank_commander:1) g(medium4) b(mt) cd2(480) ci2(60) cw(6) cp(22)
	cost(430))
}
{"su76i"
	("vehicle2" period(mid) year(mid) cd(480) ci(60) t(medium) side(rus) crew1(tankman:3) crew2(tank_commander:1) g(medium2) b(td) cd2(480) ci2(60) cw(6) cp(25)
	cost(460))
}
{"kv1_122"
	("vehicle2" period(mid) year(mid) cd(0) ci(0) t(heavy) side(rus) crew1(tankman:4) crew2(tank_commander:1) g(heavy3) b(art) cd2(900) ci2(60) cw(8) cp(30)
	cost(870))
}
{"kv2_39"
	("vehicle2" period(mid) year(mid) cd(0) ci(0) t(heavy) side(rus) crew1(tankman:5) crew2(tank_commander:1) g(heavy4) b(art) cd2(900) ci2(60) cw(8) cp(30)
	cost(920))
}
