{"76mm_pak36r"
	("vehicle"  period(mid) year(mid) cd(240) ci(60)  t(vehicle) side(ger) crew(rifleman_1:4) g(wheel6) b(support) cd2(240) ci2(60) cw(2) cp(5)
	cost(100))
}
{"flakpanzer1a"
	("vehicle2" period(mid) year(mid) cd(60) ci(60) t(light) side(ger) crew1(tankman:2) crew2(tank_commander:1) g(light2) b(lt) cd2(60) ci2(60) cw(4) cp(12)
	cost(230))
}
{"panzer2j"
	("vehicle2" period(mid) year(mid) cd(90) ci(60) t(light) side(ger) crew1(tankman:2) crew2(tank_commander:1) g(light2) b(lt) cd2(90) ci2(60) cw(4) cp(15)
	cost(300))
}
{"sdkfz251c_9"
	("vehicle2"  period(mid) year(mid) cd(90) ci(30) t(vehicle) side(ger) crew1(rifleman_1:1) crew2(artilleryman:3) g(wheel10) b(lt) cd2(90) ci2(30) cw(2) cp(13)
	cost(380))
}
{"panzer3l_pak38"
	("vehicle2" period(mid) year(mid) cd(0) ci(0) t(medium) side(ger) crew1(tankman:4) crew2(tank_commander:1) g(medium2) b(mt) cd2(480) ci2(60) cw(6) cp(15)
	cost(405))
}
{"panzer4f1_shielded"
	("vehicle2" period(mid) year(mid) cd(480) ci(60) t(medium) side(ger) crew1(tankman:4) crew2(tank_commander:1) g(medium3) b(mt) cd2(480) ci2(60) cw(6) cp(15)
	cost(445))
}
{"marder139"
	("vehicle2" period(mid) year(mid) cd(480) ci(60) t(light) side(ger) crew1(tankman_stug:3) crew2(tank_commander:1) g(spg1) b(td) cd2(480) ci2(60) cw(6) cp(20)
	cost(420))
}
{"dicker_max"
	("vehicle2" period(mid) year(mid) cd(600) ci(180) t(medium heavyart) side(ger) crew1(tankman_stug:3) crew2(tank_commander_stug:1) g(spg6) b(td) cd2(600) ci2(180) cw(6) cp(30)
	cost(800)) 
}
{"geschuetzwagen_ivb"
	("vehicle2" period(mid) year(mid) cd(600) ci(180) t(medium heavyart) side(ger) crew1(tankman_stug:3) crew2(tank_commander_stug:1) g(spg6) b(art) cd2(600) ci2(180) cw(6) cp(30)
	cost(800)) 
}
{"b1sf"
	("vehicle2" period(mid) year(mid) cd(600) ci(180) t(medium heavyart) side(ger) crew1(tankman_stug:3) crew2(tank_commander_stug:1) g(spg6) b(art) cd2(600) ci2(180) cw(6) cp(30)
	cost(1000)) 
}
