	{Entity "uk-beaufighter" 0x82f3
		{Position 7199.14 -8930}
		{xform zl 90}
		{Extender "detail"
			{random}
		}
		{DisableObstacles}
		{Player 0}
		{MID 317}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "douglas" 0x82f5
		{Position 7575.14 -8930}
		{xform zl 90}
		{DisableObstacles}
		{Player 0}
		{MID 318}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "ca101_b" 0x82f6
		{Position 7981.29 -8930}
		{xform zl 90}
		{Extender "enumerator"
			{number 810}
			{digit_folder "red"}
		}
		{Extender "detail"
			{random}
		}
		{DisableObstacles}
		{Player 0}
		{MID 319}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "sm79" 0x82f8
		{Position 7399.14 -8630}
		{xform zl 90}
		{DisableObstacles}
		{Player 0}
		{MID 320}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "a6m21_reisen" 0x82f9
		{Position 6891.93 -8930}
		{xform zl 90}
		{TexMod ""}
		{DisableObstacles}
		{Player 0}
		{MID 321}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "b25_pol" 0x82fa
		{Position 6521.96 -8930}
		{xform zl 90}
		{DisableObstacles}
		{Player 0}
		{MID 322}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Entity "us-b25" 0x8305
		{Position 6064.04 -8930}
		{xform zl 90}
		{DisableObstacles}
		{Player 0}
		{MID 323}
		{Able "-emit_passangers_on_enemy"}
		{Weaponry
			{Current "bomb"}
		}
		{Chassis "airborne"
			{AirborneMode 1}
			{Altitude 47}
		}
		{ChassisManager
			{Current "airborne"}
		}
	}
	{Human "mp/usaf/mid/pilot" 0x8310
		{Position 6063.98 -8850.76}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 324}
		{NameId 90 0}
	}
	{Human "mp/usaf/mid/pilot" 0x8311
		{Position 6063.98 -8811.27}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 325}
		{NameId 31 57}
	}
	{Human "mp/usaf/mid/pilot" 0x8312
		{Position 6063.98 -8889.53}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 326}
		{NameId 112 27}
	}
	{Human "mp/pol/mid/pilot" 0x8313
		{Position 6521.9 -8850.76}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 330}
		{NameId 23 47}
	}
	{Human "mp/pol/mid/pilot" 0x8314
		{Position 6521.9 -8889.53}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 331}
		{NameId 2 98}
	}
	{Human "mp/pol/mid/pilot" 0x8315
		{Position 6521.9 -8811.27}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 332}
		{NameId 47 101}
	}
	{Human "mp/jap/mid/pilot" 0x8317
		{Position 6891 -8911.8}
		{xform zl 180 y 7.42 zw -89.42}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 334}
		{NameId 229 25}
	}
	{Human "mp/uk/mid/pilot" 0x8318
		{Position 7199.14 -8903.25}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 335}
		{NameId 4 12}
	}
	{Human "mp/uk/mid/pilot" 0x8319
		{Position 7199.15 -8983.49}
		{xform zl 180 y 38.26 zw 90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 336}
		{NameId 12 94}
	}
	{Human "mp/fra/mid/pilot" 0x831a
		{Position 7575.13 -8970.49}
		{xform zl 180 y 3.96 zw 90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 337}
		{NameId 7 14}
	}
	{Human "mp/fra/mid/pilot" 0x831b
		{Position 7575.14 -8878}
		{xform zl 180 y 8.45 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 338}
		{NameId 3 13}
	}
	{Human "mp/fra/mid/pilot" 0x831c
		{Position 7575.14 -8849.59}
		{xform zl 180 y 17.99 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 339}
		{NameId 10 14}
	}
	{Human "mp/hun/mid/pilot" 0x831d
		{Position 7989.11 -8840.9}
		{xform zl 90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 342}
		{NameId 0 4}
	}
	{Human "mp/hun/mid/pilot" 0x831e
		{Position 7973.26 -8840.9}
		{xform zl 90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 343}
		{NameId 17 9}
	}
	{Human "mp/hun/mid/pilot" 0x831f
		{Position 7981.32 -8921.93}
		{xform zl -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 344}
		{NameId 26 13}
	}
	{Human "mp/ita/mid/pilot" 0x8320
		{Position 8381.32 -8900.53}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 345}
		{NameId 25 124}
	}
	{Human "mp/ita/mid/pilot" 0x8321
		{Position 8371.67 -8900.53}
		{xform zl 180 y 15.15 zw -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 346}
		{NameId 35 16}
	}
	{Human "mp/ita/mid/pilot" 0x8322
		{Position 8376.56 -8927.96}
		{xform zl -90}
		{Volume "body"
			{able {blast 0}}
		}
		{Volume "head"
			{able {blast 0}}
		}
		{Volume "face"
			{able {blast 0}}
		}
		{Volume "arm1l"
			{able {blast 0}}
		}
		{Volume "arm2l"
			{able {blast 0}}
		}
		{Volume "arm1r"
			{able {blast 0}}
		}
		{Volume "arm2r"
			{able {blast 0}}
		}
		{Volume "foot1r"
			{able {blast 0}}
		}
		{Volume "foot2r"
			{able {blast 0}}
		}
		{Volume "foot1l"
			{able {blast 0}}
		}
		{Volume "foot2l"
			{able {blast 0}}
		}
		{Volume "ram"
			{able {visible 0}{bullet 0}{throwing 0}{obstacle 0}{contact 0}{contact_ground 0}{blast 0}{select 0}{touch 0}{blockcamera 0}}
			{disabled}
		}
		{Player 0}
		{MID 347}
		{NameId 92 115}
	}
	{Link 0x8318 {0x82f3 "driver"}}
	{Link 0x8319 {0x82f3 "gunner"}}
	{Link 0x831b {0x82f5 "driver"}}
	{Link 0x831c {0x82f5 "gunner"}}
	{Link 0x831a {0x82f5 "gunner1"}}
	{Link 0x831f {0x82f6 "gunner"}}
	{Link 0x831d {0x82f6 "driver"}}
	{Link 0x831e {0x82f6 "commander"}}
	{Link 0x8320 {0x82f8 "driver"}}
	{Link 0x8321 {0x82f8 "commander"}}
	{Link 0x8322 {0x82f8 "gunner"}}
	{Link 0x8317 {0x82f9 "driver"}}
	{Link 0x8313 {0x82fa "driver"}}
	{Link 0x8315 {0x82fa "gunner"}}
	{Link 0x8314 {0x82fa "gunner2"}}
	{Link 0x8310 {0x8305 "driver"}}
	{Link 0x8311 {0x8305 "gunner"}}
	{Link 0x8312 {0x8305 "gunner2"}}
	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "airstrike_uk" "move_fast" 0x82f3}
	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "airstrike_fra" "move_fast" 0x82f5}
	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "airstrike_hun" "move_fast" 0x82f6}
	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "airstrike_ita" "move_slow" 0x82f8}
	{Tags "engine_count_1" "hidden" "air_vehicle" "no_scavenge" "airstrike_jap" "move_fast" 0x82f9}
	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "airstrike_pol" "move_fast" 0x82fa}
	{Tags "engine_count_2" "hidden" "air_vehicle" "no_scavenge" "airstrike_usaf" "move_fast" 0x8305}
	{Tags "pilot" 0x8310}
	{Tags "pilot" 0x8311}
	{Tags "pilot" 0x8312}
	{Tags "pilot" 0x8313}
	{Tags "pilot" 0x8314}
	{Tags "pilot" 0x8315}
	{Tags "pilot" 0x8317}
	{Tags "pilot" 0x8318}
	{Tags "pilot" 0x8319}
	{Tags "pilot" 0x831a}
	{Tags "pilot" 0x831b}
	{Tags "pilot" 0x831c}
	{Tags "pilot" 0x831d}
	{Tags "pilot" 0x831e}
	{Tags "pilot" 0x831f}
	{Tags "pilot" 0x8320}
	{Tags "pilot" 0x8321}
	{Tags "pilot" 0x8322}
	{Inventory 0x8310
		{box
			{clear}
			{item "us-colt" filled {cell 0 0}}
			{item "11x23" "ammo" 10 {cell 2 0}}
			{item "11x23" "ammo" 10 {cell 3 0}}
			{item "11x23" "ammo" 10 {cell 4 0}}
			{item "11x23" "ammo" 10 {cell 5 0}}
			{item "11x23" "ammo" 10 {cell 6 0}}
			{item "11x23" "ammo" 10 {cell 7 0}}
			{item "11x23" "ammo" 10 {cell 0 1}}
			{item "11x23" "ammo" 10 {cell 1 1}}
			{item "11x23" "ammo" 10 {cell 2 1}}
			{item "11x23" "ammo" 10 {cell 3 1}}
			{item "11x23" "ammo" 5 {cell 4 1}}
			{item "us-bandage" {cell 5 1}}
			{item "us-helmet_pilot" {cell 0 2}{user "head"}}
		}
	}
	{Inventory 0x8311
		{box
			{clear}
			{item "us-colt" filled {cell 0 0}}
			{item "11x23" "ammo" 10 {cell 2 0}}
			{item "11x23" "ammo" 10 {cell 3 0}}
			{item "11x23" "ammo" 10 {cell 4 0}}
			{item "11x23" "ammo" 10 {cell 5 0}}
			{item "11x23" "ammo" 10 {cell 6 0}}
			{item "11x23" "ammo" 10 {cell 7 0}}
			{item "11x23" "ammo" 10 {cell 0 1}}
			{item "11x23" "ammo" 10 {cell 1 1}}
			{item "11x23" "ammo" 10 {cell 2 1}}
			{item "11x23" "ammo" 10 {cell 3 1}}
			{item "11x23" "ammo" 5 {cell 4 1}}
			{item "us-bandage" {cell 5 1}}
			{item "us-helmet_pilot" {cell 0 2}{user "head"}}
		}
	}
	{Inventory 0x8312
		{box
			{clear}
			{item "us-colt" filled {cell 0 0}}
			{item "11x23" "ammo" 10 {cell 2 0}}
			{item "11x23" "ammo" 10 {cell 3 0}}
			{item "11x23" "ammo" 10 {cell 4 0}}
			{item "11x23" "ammo" 10 {cell 5 0}}
			{item "11x23" "ammo" 10 {cell 6 0}}
			{item "11x23" "ammo" 10 {cell 7 0}}
			{item "11x23" "ammo" 10 {cell 0 1}}
			{item "11x23" "ammo" 10 {cell 1 1}}
			{item "11x23" "ammo" 10 {cell 2 1}}
			{item "11x23" "ammo" 10 {cell 3 1}}
			{item "11x23" "ammo" 5 {cell 4 1}}
			{item "us-bandage" {cell 5 1}}
			{item "us-helmet_pilot" {cell 0 2}{user "head"}}
		}
	}
	{Inventory 0x8313
		{box
			{clear}
			{item "uk-webley" filled {cell 0 0}}
			{item "11x21" "ammo" 10 {cell 2 0}}
			{item "11x21" "ammo" 10 {cell 3 0}}
			{item "11x21" "ammo" 10 {cell 4 0}}
			{item "11x21" "ammo" 10 {cell 5 0}}
			{item "11x21" "ammo" 10 {cell 6 0}}
			{item "11x21" "ammo" 10 {cell 7 0}}
			{item "11x21" "ammo" 10 {cell 0 1}}
			{item "11x21" "ammo" 10 {cell 1 1}}
			{item "11x21" "ammo" 10 {cell 2 1}}
			{item "bandage_pol" {cell 3 1}}
			{item "cap_pol_eng_sidecap_radiohead" {cell 5 1}{user "head"}}
		}
	}
	{Inventory 0x8314
		{box
			{clear}
			{item "uk-webley" filled {cell 0 0}}
			{item "11x21" "ammo" 10 {cell 2 0}}
			{item "11x21" "ammo" 10 {cell 3 0}}
			{item "11x21" "ammo" 10 {cell 4 0}}
			{item "11x21" "ammo" 10 {cell 5 0}}
			{item "11x21" "ammo" 10 {cell 6 0}}
			{item "11x21" "ammo" 10 {cell 7 0}}
			{item "11x21" "ammo" 10 {cell 0 1}}
			{item "11x21" "ammo" 10 {cell 1 1}}
			{item "11x21" "ammo" 10 {cell 2 1}}
			{item "bandage_pol" {cell 3 1}}
			{item "cap_pol_eng_sidecap_radiohead" {cell 5 1}{user "head"}}
		}
	}
	{Inventory 0x8315
		{box
			{clear}
			{item "uk-webley" filled {cell 0 0}}
			{item "11x21" "ammo" 10 {cell 2 0}}
			{item "11x21" "ammo" 10 {cell 3 0}}
			{item "11x21" "ammo" 10 {cell 4 0}}
			{item "11x21" "ammo" 10 {cell 5 0}}
			{item "11x21" "ammo" 10 {cell 6 0}}
			{item "11x21" "ammo" 10 {cell 7 0}}
			{item "11x21" "ammo" 10 {cell 0 1}}
			{item "11x21" "ammo" 10 {cell 1 1}}
			{item "11x21" "ammo" 10 {cell 2 1}}
			{item "bandage_pol" {cell 3 1}}
			{item "cap_pol_eng_sidecap_radiohead" {cell 5 1}{user "head"}}
		}
	}
	{Inventory 0x8317
		{box
			{clear}
			{item "nambu" filled {cell 0 0}}
			{item "8x22" "ammo" 10 {cell 2 0}}
			{item "8x22" "ammo" 10 {cell 3 0}}
			{item "8x22" "ammo" 10 {cell 4 0}}
			{item "8x22" "ammo" 10 {cell 5 0}}
			{item "8x22" "ammo" 10 {cell 6 0}}
			{item "8x22" "ammo" 10 {cell 7 0}}
			{item "8x22" "ammo" 10 {cell 0 1}}
			{item "8x22" "ammo" 10 {cell 1 1}}
			{item "8x22" "ammo" 10 {cell 2 1}}
			{item "8x22" "ammo" 10 {cell 3 1}}
			{item "8x22" "ammo" 10 {cell 4 1}}
			{item "8x22" "ammo" 10 {cell 5 1}}
			{item "bandage_jap" {cell 6 1}}
			{item "jappilot_cap" {cell 0 2}{user "head"}}
		}
	}
	{Inventory 0x8318
		{box
			{clear}
			{item "uk-webley" filled {cell 0 0}}
			{item "11x21" "ammo" 10 {cell 2 0}}
			{item "11x21" "ammo" 10 {cell 3 0}}
			{item "11x21" "ammo" 10 {cell 4 0}}
			{item "11x21" "ammo" 10 {cell 5 0}}
			{item "11x21" "ammo" 10 {cell 6 0}}
			{item "11x21" "ammo" 10 {cell 7 0}}
			{item "11x21" "ammo" 10 {cell 0 1}}
			{item "11x21" "ammo" 10 {cell 1 1}}
			{item "11x21" "ammo" 10 {cell 2 1}}
			{item "uk-bandage" {cell 3 1}}
			{item "uk-helmet_pilot" {cell 5 1}{user "head"}}
		}
	}
	{Inventory 0x8319
		{box
			{clear}
			{item "uk-webley" filled {cell 0 0}}
			{item "11x21" "ammo" 10 {cell 2 0}}
			{item "11x21" "ammo" 10 {cell 3 0}}
			{item "11x21" "ammo" 10 {cell 4 0}}
			{item "11x21" "ammo" 10 {cell 5 0}}
			{item "11x21" "ammo" 10 {cell 6 0}}
			{item "11x21" "ammo" 10 {cell 7 0}}
			{item "11x21" "ammo" 10 {cell 0 1}}
			{item "11x21" "ammo" 10 {cell 1 1}}
			{item "11x21" "ammo" 10 {cell 2 1}}
			{item "uk-bandage" {cell 3 1}}
			{item "uk-helmet_pilot" {cell 5 1}{user "head"}}
		}
	}
	{Inventory 0x831a
		{box
			{clear}
			{item "ruby" filled {cell 0 0}}
			{item "7x17" "ammo" 15 {cell 2 0}}
			{item "7x17" "ammo" 15 {cell 3 0}}
			{item "7x17" "ammo" 15 {cell 4 0}}
			{item "7x17" "ammo" 15 {cell 5 0}}
			{item "7x17" "ammo" 15 {cell 6 0}}
			{item "7x17" "ammo" 15 {cell 7 0}}
			{item "bandage_fra" {cell 0 1}}
			{item "cap_fra_pilot" {cell 2 1}{user "head"}}
		}
	}
	{Inventory 0x831b
		{box
			{clear}
			{item "ruby" filled {cell 0 0}}
			{item "7x17" "ammo" 15 {cell 2 0}}
			{item "7x17" "ammo" 15 {cell 3 0}}
			{item "7x17" "ammo" 15 {cell 4 0}}
			{item "7x17" "ammo" 15 {cell 5 0}}
			{item "7x17" "ammo" 15 {cell 6 0}}
			{item "7x17" "ammo" 15 {cell 7 0}}
			{item "bandage_fra" {cell 0 1}}
			{item "cap_fra_pilot" {cell 2 1}{user "head"}}
		}
	}
	{Inventory 0x831c
		{box
			{clear}
			{item "ruby" filled {cell 0 0}}
			{item "7x17" "ammo" 15 {cell 2 0}}
			{item "7x17" "ammo" 15 {cell 3 0}}
			{item "7x17" "ammo" 15 {cell 4 0}}
			{item "7x17" "ammo" 15 {cell 5 0}}
			{item "7x17" "ammo" 15 {cell 6 0}}
			{item "7x17" "ammo" 15 {cell 7 0}}
			{item "bandage_fra" {cell 0 1}}
			{item "cap_fra_pilot" {cell 2 1}{user "head"}}
		}
	}
	{Inventory 0x831d
		{box
			{clear}
			{item "frommer_37m" filled {cell 0 0}}
			{item "9x17" "ammo" 15 {cell 2 0}}
			{item "9x17" "ammo" 15 {cell 3 0}}
			{item "9x17" "ammo" 15 {cell 4 0}}
			{item "9x17" "ammo" 15 {cell 5 0}}
			{item "9x17" "ammo" 15 {cell 6 0}}
			{item "9x17" "ammo" 15 {cell 7 0}}
			{item "9x17" "ammo" 15 {cell 0 1}}
			{item "bandage_hun" {cell 1 1}}
			{item "helmet_hun_pilot" {cell 3 1}{user "head"}}
		}
	}
	{Inventory 0x831e
		{box
			{clear}
			{item "frommer_37m" filled {cell 0 0}}
			{item "9x17" "ammo" 15 {cell 2 0}}
			{item "9x17" "ammo" 15 {cell 3 0}}
			{item "9x17" "ammo" 15 {cell 4 0}}
			{item "9x17" "ammo" 15 {cell 5 0}}
			{item "9x17" "ammo" 15 {cell 6 0}}
			{item "9x17" "ammo" 15 {cell 7 0}}
			{item "9x17" "ammo" 15 {cell 0 1}}
			{item "bandage_hun" {cell 1 1}}
			{item "helmet_hun_pilot" {cell 3 1}{user "head"}}
		}
	}
	{Inventory 0x831f
		{box
			{clear}
			{item "frommer_37m" filled {cell 0 0}}
			{item "9x17" "ammo" 15 {cell 2 0}}
			{item "9x17" "ammo" 15 {cell 3 0}}
			{item "9x17" "ammo" 15 {cell 4 0}}
			{item "9x17" "ammo" 15 {cell 5 0}}
			{item "9x17" "ammo" 15 {cell 6 0}}
			{item "9x17" "ammo" 15 {cell 7 0}}
			{item "9x17" "ammo" 15 {cell 0 1}}
			{item "bandage_hun" {cell 1 1}}
			{item "helmet_hun_pilot" {cell 3 1}{user "head"}}
		}
	}
	{Inventory 0x8320
		{box
			{clear}
			{item "beretta_m1934" filled {cell 0 0}}
			{item "9x17" "ammo" 15 {cell 2 0}}
			{item "9x17" "ammo" 15 {cell 3 0}}
			{item "9x17" "ammo" 15 {cell 4 0}}
			{item "9x17" "ammo" 15 {cell 5 0}}
			{item "9x17" "ammo" 15 {cell 6 0}}
			{item "9x17" "ammo" 15 {cell 7 0}}
			{item "9x17" "ammo" 15 {cell 0 1}}
			{item "bandage_ita" {cell 1 1}}
			{item "cap_ita_bustina" {cell 3 1}{user "head"}}
		}
	}
	{Inventory 0x8321
		{box
			{clear}
			{item "beretta_m1934" filled {cell 0 0}}
			{item "9x17" "ammo" 15 {cell 2 0}}
			{item "9x17" "ammo" 15 {cell 3 0}}
			{item "9x17" "ammo" 15 {cell 4 0}}
			{item "9x17" "ammo" 15 {cell 5 0}}
			{item "9x17" "ammo" 15 {cell 6 0}}
			{item "9x17" "ammo" 15 {cell 7 0}}
			{item "9x17" "ammo" 15 {cell 0 1}}
			{item "bandage_ita" {cell 1 1}}
			{item "cap_ita_bustina" {cell 3 1}{user "head"}}
		}
	}
	{Inventory 0x8322
		{box
			{clear}
			{item "beretta_m1934" filled {cell 0 0}}
			{item "9x17" "ammo" 15 {cell 2 0}}
			{item "9x17" "ammo" 15 {cell 3 0}}
			{item "9x17" "ammo" 15 {cell 4 0}}
			{item "9x17" "ammo" 15 {cell 5 0}}
			{item "9x17" "ammo" 15 {cell 6 0}}
			{item "9x17" "ammo" 15 {cell 7 0}}
			{item "9x17" "ammo" 15 {cell 0 1}}
			{item "bandage_ita" {cell 1 1}}
			{item "cap_ita_bustina" {cell 3 1}{user "head"}}
		}
	}
		{Brain 0x8310
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8311
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8312
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8313
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8314
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8315
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8317
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8318
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8319
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x831a
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x831b
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x831c
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x831d
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x831e
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x831f
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8320
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8321
		{Properties
			{retreat_ratio 4}
		}
	}
	{Brain 0x8322
		{Properties
			{retreat_ratio 4}
		}
	}
	
