
;/*=========== Sound defines Begin ===========*/

(define "m4_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4/full"}
		{link_sound "exhaust"			"vehicle/engine/m4/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m4a2_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4a2/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4a2/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4a2/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4a2/full"}
		{link_sound "exhaust"			"vehicle/engine/m4a2/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m4a3_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4a3/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4a3/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4a3/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4a3/full"}
		{link_sound "exhaust"			"vehicle/engine/m4a3/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4a2"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m4a4_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4a4/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4a4/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4a4/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4a4/full"}
		{link_sound "exhaust"			"vehicle/engine/m4a4/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m3lee_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3lee/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3lee/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3lee/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3lee/full"}
		{link_sound "exhaust"			"vehicle/engine/m3lee/exhaust"}
		{link_sound "move"			"vehicle/tracks/m7"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m7_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3lee/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3lee/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3lee/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3lee/full"}
		{link_sound "exhaust"			"vehicle/engine/m3lee/exhaust"}
		{link_sound "move"			"vehicle/tracks/m7"}
		{link_sound "rotate_turret" 		"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
	}
)
(define "m3stuart_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3stuart/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3stuart/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3stuart/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3stuart/full"}
		{link_sound "exhaust"			"vehicle/engine/m3stuart/exhaust"}
		{link_sound "move"			"vehicle/tracks/m3a1_stuart"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}
	}
)
(define "m24_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m24/start"}
		{link_sound "engine_stop"		"vehicle/engine/m24/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m24/idle"}
		{link_sound "engine_full"		"vehicle/engine/m24/full"}
		{link_sound "exhaust"			"vehicle/engine/m24/exhaust"}
		{link_sound "move"			"vehicle/tracks/m24"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m26_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m26/start"}
		{link_sound "engine_stop"		"vehicle/engine/m26/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m26/idle"}
		{link_sound "engine_full"		"vehicle/engine/m26/full"}
		{link_sound "exhaust"			"vehicle/engine/m26/exhaust"}
		{link_sound "move"			"vehicle/tracks/m26"}
		{link_sound "rotate_turret"		"vehicle/turret/hydraulic/hydraulic_heavy"}
	}
)
(define "us_halftrack_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/us_halftrack/start"}
		{link_sound "engine_stop"		"vehicle/engine/us_halftrack/stop"}
		{link_sound "engine_idle"		"vehicle/engine/us_halftrack/idle"}
		{link_sound "engine_full"		"vehicle/engine/us_halftrack/full"}
		{link_sound "exhaust"			"vehicle/engine/us_halftrack/exhaust"}
		{link_sound "move"			"vehicle/tracks/m3a1"}
		{link_sound "rotate_turret" 		"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
	}
)
(define "m8grayhound_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m8grayhound/start"}
		{link_sound "engine_stop"		"vehicle/engine/m8grayhound/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m8grayhound/idle"}
		{link_sound "engine_full"		"vehicle/engine/m8grayhound/full"}
		{link_sound "exhaust"			"vehicle/engine/m8grayhound/exhaust"}
		{link_sound "move"			"vehicle/wheels/truck"}
		{link_sound "brake"			"vehicle/wheels/brake"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
(define "m10_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4/full"}
		{link_sound "exhaust"			"vehicle/engine/m4/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret" 		"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
	}
)
(define "m5hst_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3stuart/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3stuart/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3stuart/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3stuart/full"}
		{link_sound "exhaust"			"vehicle/engine/m3stuart/exhaust"}
		{link_sound "move"			"vehicle/tracks/m3a1_stuart"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}
	}
)
(define "crusader_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/crusader/start"}
		{link_sound "engine_stop"		"vehicle/engine/crusader/stop"}
		{link_sound "engine_idle"		"vehicle/engine/crusader/idle"}
		{link_sound "engine_full"		"vehicle/engine/crusader/full"}
		{link_sound "exhaust"			"vehicle/engine/crusader/exhaust"}
		{link_sound "move"			"vehicle/tracks/crusader"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
;/*=========== Sound defines End ===========*/

;/*=========== USAF tanks Begin ===========*/
{"np_m3a1_scout tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m3a1_scout_tr tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m20 tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m8_grayhound tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
		("M2HB")
	}
}
{"np_m8_grayhound_2 tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
		("M2HB")
	}
}
{"np_m4halftrack tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Mortar_8cm")
	}
}
{"np_t30hmc tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}
{"np_t12gmc tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("Cannon_Breech")
	}
}
{"np_t19hmc tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")

		("M2HB")
	}
}
{"np_m15a1 tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M2HB_M33_Mount")
	}
}
{"np_m22 tank" 
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"np_m3_stuart tank" 
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"np_m3_stuart_early tank" 
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"np_m3_satan" 
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("M1919A4")
	}
	{on spawn
		{add_view "flamer_fire_tank" "flame" "foresight1"}
		{add_view "flamer_fire_barrel" "fire" "foresight1"}
	}
	{on operatable on
		{view start "fire"}
	}
	{on operatable off
		{view stop "fire"}
	}
	{on "_explosion"
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	("flame_weapon" args gun 60 1 40)
}
{"np_m5a1 tank"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"np_m8 tank"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}
{"np_m3lee tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		{link_sound 		"action_recoil_Cannon2"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
		{link_sound	 	"Cannon_Mid2"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm/"}
		{link_sound 		"Cannon_Far2"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm/"}
		("M1919A4")
	}
}
{"np_m4a1 tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M1919A4")
	}
}
{"np_m4 tank"	
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	
{"np_m10wolverine tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m7 tank"
	("m7_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}
{"np_m4a3c tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M1919A4")
	}
}
{"np_m4a3_zippo tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on spawn
		{add_view "flamer_fire_tank" "flame" "foresight5"}
		{add_view "flamer_fire_barrel" "fire" "foresight5"}
	}
	{on operatable on
		{view start "fire"}
	}
	{on operatable off
		{view stop "fire"}
	}
	{on "_explosion"
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	("flame_weapon" args flamer1 60 1 40)
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m12gmc tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("Cannon_150to210mm")
		("Cannon_Breech")
	}
}
{"np_m4a3_105 tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a3e2_jumbo_76w tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a3e2_jumbo tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a2 tank"	
	("m4a2_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	
{"np_m4a3_75 tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a3_76 tank"	
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}	
{"np_m26_pershing tank"
	("m26_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M1919A4")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m26_veteran tank"
	("m26_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M1919A4")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m26e4_pershing tank"
	("m26_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M1919A4")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m18 tank"
	("m24_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("Cannon_Breech")
		("M2HB")
	}
}
{"np_m24_chaffee tank"
	("m24_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M1919A4")
	}
}
{"np_m3 tank"
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m36gmc tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m36b2 tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("Cannon_Breech")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m36b1 tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("Cannon_Breech")
		("M2HB")
	}
}
{"np_m4a3e8 tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a3e8_armor tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a1e8 tank"	
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"np_m2halftrack"
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
		("M1919A4")
	}
}
{"np_m2a4"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"np_m1a1_car"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("M2HB")
		("M1919A4")
	}
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"np_m2a1_lt"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("M2HB")
		("M1919A4")
	}
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"np_m2halftrack"
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
		("M1919A4")
	}
}
{"np_m2a4"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"np_m1a1_car"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("M2HB")
		("M1919A4")
	}
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"np_m2a1_lt"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("M2HB")
		("M1919A4")
	}
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"np_m16 tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB_M45_Mount")
	}
	{on spawn
		{link_sound "bkg_hmg" "weapon/shot/bkg/gun/hmg/"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel00"	"shooter00"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel01"	"shooter01"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel02"	"shooter02"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel03"	"shooter03"}
		{add_view "zenit_gilz"			"shell"			"FXshell1"}
		{add_view "zenit_gilz"			"shell"			"FXshell2"}
		{add_view "zenit_gilz"			"shell"			"FXshell3"}
		{add_view "zenit_gilz"			"shell"			"FXshell4"}
	}
	{on fire "mgun1" overload
		(define "fire_barrel"
			name "%0"
				{call "fire_barrel%0"}
				{view start "flashbarrel%0"}
				{ani_play "fire%0"}
				{delay 0.2
					{view pause "flashbarrel%0"}
				}
		)
		{if	("fire_barrel" args 00)
		else ("fire_barrel" args 01)
		else ("fire_barrel" args 02)
		else ("fire_barrel" args 03)
		}
		{play_sound "bkg_hmg"}
		{ani_play "recoil"}
		{call "spawn_shell"}
	}
}
{"np_m4hst"
	("m5hst_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}	
{"np_lvt4_wb2"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("M1919A4")
	}
}
{"np_t26e4 tank"
	("m26_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M1919A4")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a1_76_w tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"np_m4a3e8_fury tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"np_m18_90 tank"
	("m24_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M2HB")
	}
}
{"np_t29 tank"
	("m26_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M1919A4")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_t26e2 tank"
	("m26_sound")
	{on "add_weapon_sound" overload
		("Cannon_85to100mm")
		("M1919A4")
		("M2HB")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4_105 tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
;/*=========== USAF tanks End ===========*/
	
;/*=========== French late Begin ===========*/
{"m4a1e8_fr tank"	
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	
{"m5a1_fr tank"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"m8_fr tank"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}
{"m3lee_fr tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		{link_sound 		"action_recoil_Cannon2"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
		{link_sound	 	"Cannon_Mid2"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm/"}
		{link_sound 		"Cannon_Far2"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm/"}
		("M1919A4")
	}
}
{"m4a3_75_fr tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a3_76_fr tank"	
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}	
{"m10wolverine_fr tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}		
}
{"m10_early_fr"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}		
}
{"m7_fr tank"
	("m7_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}
{"m3a1_scout_fr tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"m20_fr tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"m8_grayhound_fr tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
		("M2HB")
	}
}
{"m4halftrack_fr tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Mortar_8cm")
	}
}
{"m3halftrack_fr tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"m17_fr tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB_M45_Mount")
	}
	{on spawn
		{link_sound "bkg_hmg" "weapon/shot/bkg/gun/hmg/"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel00"	"shooter00"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel01"	"shooter01"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel02"	"shooter02"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel03"	"shooter03"}
		{add_view "zenit_gilz"			"shell"			"FXshell1"}
		{add_view "zenit_gilz"			"shell"			"FXshell2"}
		{add_view "zenit_gilz"			"shell"			"FXshell3"}
		{add_view "zenit_gilz"			"shell"			"FXshell4"}
	}
	{on fire "mgun1" overload
		(define "fire_barrel"
			name "%0"
				{call "fire_barrel%0"}
				{view start "flashbarrel%0"}
				{ani_play "fire%0"}
				{delay 0.2
					{view pause "flashbarrel%0"}
				}
		)
		{if	("fire_barrel" args 00)
		else ("fire_barrel" args 01)
		else ("fire_barrel" args 02)
		else ("fire_barrel" args 03)
		}
		{play_sound "bkg_hmg"}
		{ani_play "recoil"}
		{call "spawn_shell"}
	}
}
{"m4a3_105_fr tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"cavalier_mk_vii tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"m3_stuart_fr tank" 
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"m4a2_fr tank"	
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	
{"t12gmc_fr tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("Cannon_Breech")
	}
}
{"m2halftrack_fr tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"m12gmc_fr tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("Cannon_150to210mm")
		("Cannon_Breech")
	}
}
{"m4hst_fr"
	("m5hst_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
;/*=========== French late End ===========*/

;/*=========== British lend-lease Begin ===========*/
{"np_m4a2 tank"	
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"np_m10wolverine tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}		
}
{"np_m3lee tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		{link_sound 		"action_recoil_Cannon2"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
		{link_sound	 	"Cannon_Mid2"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm/"}
		{link_sound 		"Cannon_Far2"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm/"}
		("M1919A4")
	}
}
{"np_m3a1_scout tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m7 tank"
	("m7_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}
{"np_m3grant tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		{link_sound 		"action_recoil_Cannon2"	"weapon/shot/cannon/s2/recoil/Shared/Cannon/"}
		{link_sound	 	"Cannon_Mid2"		"weapon/shot/cannon/s3/d2/Shared/Cannon_75to76mm/"}
		{link_sound 		"Cannon_Far2"		"weapon/shot/cannon/s3/d3/Shared/Cannon_75to76mm/"}
		("M1919A4")
	}
}
{"np_m3a1_scout_tr tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m4a3_105 tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a4 tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a4_firefly tank"	
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a1_76 tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"np_achilles tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m3halftrack tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_m4a4_tulip tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_m4a4_firefly_tulip tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}

;/*=========== British lend-lease End ===========*/

;/*=========== Polish lend-lease Begin ===========*/
{"m5a1_pol tank"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"m4a1_76_pol tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"m5hst_pol"
	("m5hst_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
;/*=========== Polish lend-lease End ===========*/

{"lvt4"
	("m3stuart_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("Cannon_Breech")
		("M2HB")
	}
}

(include "tank-extra.inc")
