(define "tks_sound"
	{on "add_movement_sound" overload
		{link_sound "move"			"vehicle/tracks/bt/bt_track"		}
		{link_sound "rotate_turret" 	"vehicle/turret/handcrank/handcrank_light"		}
		{link_sound "engine_full"			"vehicle/engine/tks/full"		}
		{link_sound "engine_end"		"vehicle/engine/tks/stop"	}
		{link_sound "exhaust"			"vehicle/engine/tks/start"	}
		{link_sound "engine_idle"			"vehicle/engine/tks/full"		}
	}
)
(define "wz34_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/armored_car"}
		{link_sound "brake"				"vehicle/wheels/brake"}
		{link_sound "engine_full"			"vehicle/engine/wz34/full"		}
		{link_sound "engine_end"		"vehicle/engine/wz34/stop"	}
		{link_sound "exhaust"			"vehicle/engine/wz34/start"	}
		{link_sound "rotate_turret" 	"vehicle/turret/handcrank/handcrank_light"		}
		{link_sound "engine_idle"		"vehicle/engine/ba/idle"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
(define "wz29_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/armored_car"}
		{link_sound "brake"				"vehicle/wheels/brake"}
		{link_sound "engine_full"			"vehicle/engine/wz29/full"		}
		{link_sound "engine_end"		"vehicle/engine/wz29/stop"	}
		{link_sound "exhaust"			"vehicle/engine/wz29/start"	}
		{link_sound "rotate_turret" 	"vehicle/turret/handcrank/handcrank_light"		}
		{link_sound "engine_idle"		"vehicle/engine/ba/idle"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
(define "churchill_tank_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/churchill/start"}
		{link_sound "engine_stop"		"vehicle/engine/churchill/stop"}
		{link_sound "engine_idle"		"vehicle/engine/churchill/idle"}
		{link_sound "engine_full"		"vehicle/engine/churchill/full"}
		{link_sound "exhaust"			"vehicle/engine/churchill/exhaust"}
		{link_sound "move"			"vehicle/tracks/churchill"}
		{link_sound "rotate_turret"		"vehicle/turret/churchill_turret"}
	}
)
(define "cromwell_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/cromwell/start"}
		{link_sound "engine_stop"		"vehicle/engine/cromwell/stop"}
		{link_sound "engine_idle"		"vehicle/engine/cromwell/idle"}
		{link_sound "engine_full"		"vehicle/engine/cromwell/full"}
		{link_sound "exhaust"			"vehicle/engine/cromwell/exhaust"}
		{link_sound "move"			"vehicle/tracks/cromwell"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "crusader_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/crusader/start"}
		{link_sound "engine_stop"		"vehicle/engine/crusader/stop"}
		{link_sound "engine_idle"		"vehicle/engine/crusader/idle"}
		{link_sound "engine_full"		"vehicle/engine/crusader/full"}
		{link_sound "exhaust"			"vehicle/engine/crusader/exhaust"}
		{link_sound "move"			"vehicle/tracks/crusader"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "valentine_tank_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/crusader/start"}
		{link_sound "engine_stop"		"vehicle/engine/crusader/stop"}
		{link_sound "engine_idle"		"vehicle/engine/crusader/idle"}
		{link_sound "engine_full"		"vehicle/engine/crusader/full"}
		{link_sound "exhaust"			"vehicle/engine/crusader/exhaust"}
		{link_sound "move"			"vehicle/tracks/crusader"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "daimler_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/armored_car"}
		{link_sound "brake"				"vehicle/wheels/brake"}
		{link_sound "engine_full"		"vehicle/engine/daimler/full"		}
		{link_sound "engine_end"		"vehicle/engine/daimler/stop"	}
		{link_sound "exhaust"			"vehicle/engine/daimler/start"	}
		{link_sound "rotate_turret" 	"vehicle/turret/handcrank/handcrank_light"		}
		{link_sound "engine_idle"		"vehicle/engine/daimler/idle"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
(define "dingo_sound"
	{on "add_movement_sound" overload
		{link_sound "move"				"vehicle/wheels/armored_car"}
		{link_sound "brake"				"vehicle/wheels/brake"}
		{link_sound "engine_start"		"vehicle/engine/panhard/start"}
		{link_sound "engine_full"		"vehicle/engine/Willys_MB/full"		}
		{link_sound "engine_stop"		"vehicle/engine/panhard/stop"}
		{link_sound "exhaust"			"vehicle/engine/panhard/exhaust"}
		{link_sound "rotate_turret" 	"vehicle/turret/handcrank/handcrank_light"		}
		{link_sound "engine_idle"		"vehicle/engine/dingo/idle"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
(define "aec_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/aec/start"}
		{link_sound "engine_stop"		"vehicle/engine/aec/stop"}
		{link_sound "engine_idle"		"vehicle/engine/aec/idle"}
		{link_sound "engine_full"		"vehicle/engine/aec/full"}
		{link_sound "exhaust"			"vehicle/engine/aec/exhaust"}
		{link_sound "move"			"vehicle/wheels/truck"}
		{link_sound "brake"			"vehicle/wheels/brake"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
;/*=========== Polish Vehicles Begin ===========*/
{"wz34 tank"
	("wz34_sound")
	{on "add_weapon_sound" overload
		("Hotchkiss_MG")
	}
}
{"wz34puteaux tank"
	("wz34_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm") ;Placeholder
		("Hotchkiss_MG")
	}
}
{"tks-mg tank"
	("tks_sound")
	{on "add_weapon_sound" overload
		("Hotchkiss_MG")
	}
}
{"tks-20mm tank"
	("tks_sound")
	{on "add_weapon_sound" overload
		("Autocannon_s1")
		{link_sound "action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Autocannon_20to30mm/"}
	}
}
{"vickersedw tank"
	("t26_sound")
	{on "add_weapon_sound" overload
		("Vickers_MG")
	}
} 
{"vickersejw tank"
	("t26_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("Vickers_MG")
	}
} 	
{"7tp tank"
	{on spawn
		{add_view	"flash_gun_big"	"flashbarrel00"	"shooter00"	}
		{add_view	"flash_gun_big"	"flashbarrel01"	"shooter01"	}
	}
	{on fire "mgun"
		{if  name "00"
			{view start "flashbarrel00"}
			{delay 0.5
				{view pause "flashbarrel00"}
			}
		else name "01"
			{view start "flashbarrel01"}
			{delay 0.5
				{view pause "flashbarrel01"}
			}
		}
	}
	("t26_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("Vickers_MG")
	}
}
{"10tp tank"
	("bt_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("Vickers_MG")
	}
} 
{"r35_pol tank"
	("r35_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("MAC31")
	}
} 
{"h39_pol tank"
	("h39_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("MAC31")
	}
}
{"wz29 tank"
	("wz29_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm") ;Placeholder
		("Hotchkiss_MG")
	}
	{on "lights_on"
		{ani_play "lights_on"}
		{view start "light"}
		{view show "light"}
	}
	{on "lights_off"
		{ani_play "lights_off"}
		{view stop "light"}
		{view hide "light"}
	}
}

;/*=========== Polish Vehicles End ===========*/

;/*=========== Polish lend-lease Begin ===========*/
{"m4a3_105_pol tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a4_pol tank"
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a4_firefly_pol tank"	
	("m4a3_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("M2HB")
		("M1919A4")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}	
{"achilles_pol tank"
	("m10_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("Cannon_Breech")
		("M2HB")
	}
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}
}
{"sexton_pol tank"
	("m7_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("Cannon_Breech")
		("M1919A4")
	}
}
{"dingo_pol tank" 
	("dingo_sound")
	{on "add_weapon_sound" overload
		("M1919A4")
	}
}
{"staghound_pol tank" 
	("ba_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"m3halftrack_pol tank" 
	("us_halftrack_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"cromwell_mk_iv_pol tank"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"cromwell_mk_i_pol tank"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"challenger_pol tank"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("ZB37")
	}
}
{"crusader_aa2_pol tank"
	{on spawn
		{add_view "smoke_zenit"						"zenite_smoke00"			"shooter00"}
		{add_view "tank_canon_fire_20_25_auto"		"flashbarrelzenite00"		"shooter00"}
		{add_view "smoke_zenit"						"zenite_smoke01"			"shooter01"}
		{add_view "tank_canon_fire_20_25_auto"		"flashbarrelzenite01"		"shooter01"}
		{add_view "tank_fire_zenite_dust_ground"	"zenite_ground_fx"		"basis"}
		{add_view "tank_fire_zenite_dust_sand"		"zenite_sand_fx"		"basis"}
		{add_view "tank_fire_zenite_dust_snow"		"zenite_snow_fx"		"basis"}
	}
	("crusader_sound")
	{on "add_weapon_sound" overload
		("M2HB_M33_Mount")
	}
	{on fire "gun" overload
		{if  name "00"
			{ani_play "fire01"}
			{view start "flashbarrelzenite00"}
			{view start "zenite_smoke00"}
			{delay 0.5
				{view pause "flashbarrelzenite00"}
			}
			{delay 5
				{view pause "zenite_smoke00"}
			}
		else name "01"
			{ani_play "fire02"}
			{view start "flashbarrelzenite01"}
			{view start "zenite_smoke01"}
			{delay 0.5
				{view pause "flashbarrelzenite01"}
			}
			{delay 5
				{view pause "zenite_smoke01"}
			}
		}
	}
}
{"crusader_mkii_pol tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"valentine_mkiii_pol tank" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"a10_mk2_pol" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"crusader_mki_cs_pol" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("ZB37")
	}
}
{"crusader_pol tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"mk2daimler_pol tank"
	("daimler_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"cromwell_mk_vi_pol tank"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("ZB37")
	}
}
{"churchill_mk_ii_pol"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}

;/*=========== Polish lend-lease End ===========*/

;/*=========== British Vehicles Begin ===========*/
{"np_archer tank" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
	}
	{on fire "gun" overload
		{view start "flashbarrel1"}
		{view start "flashbarrel1smoke"}
		{ani_play "fire"}
		{ani_play "fire2"}
	}
}
{"np_sexton tank"
	("m7_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("Cannon_Breech")
		("M1919A4")
	}
}
{"np_dingo tank" 
	("dingo_sound")
	{on "add_weapon_sound" overload
		("M1919A4")
	}
}
{"np_staghound tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"np_cromwell_mk_iv tank"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"np_challenger_a30 tank"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("ZB37")
	}
}
{"np_crusader_aa2 tank"
	{on spawn
		{add_view "smoke_zenit"						"zenite_smoke00"			"shooter00"}
		{add_view "tank_canon_fire_20_25_auto"		"flashbarrelzenite00"		"shooter00"}
		{add_view "smoke_zenit"						"zenite_smoke01"			"shooter01"}
		{add_view "tank_canon_fire_20_25_auto"		"flashbarrelzenite01"		"shooter01"}
		{add_view "tank_fire_zenite_dust_ground"	"zenite_ground_fx"		"basis"}
		{add_view "tank_fire_zenite_dust_sand"		"zenite_sand_fx"		"basis"}
		{add_view "tank_fire_zenite_dust_snow"		"zenite_snow_fx"		"basis"}
	}
	("crusader_sound")
	{on "add_weapon_sound" overload
		("M2HB_M33_Mount")
	}
	{on fire "gun" overload
		{if  name "00"
			{ani_play "fire01"}
			{view start "flashbarrelzenite00"}
			{view start "zenite_smoke00"}
			{delay 0.5
				{view pause "flashbarrelzenite00"}
			}
			{delay 5
				{view pause "zenite_smoke00"}
			}
		else name "01"
			{ani_play "fire02"}
			{view start "flashbarrelzenite01"}
			{view start "zenite_smoke01"}
			{delay 0.5
				{view pause "flashbarrelzenite01"}
			}
			{delay 5
				{view pause "zenite_smoke01"}
			}
		}
	}
}
{"np_crusader_mk6 tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"np_humber"
	("dingo_sound")
	{on "add_weapon_sound" overload
		("Autocannon_s1")
		("ZB37")
		{link_sound "action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Autocannon_20to30mm/"}
	}
}
{"np_churchill_avre"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_150to210mm")
	}
}
{"np_cromwell_mk_vi"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
		("ZB37")
	}
}
{"np_cromwell_75hv"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("ZB37")
	}
}
{"np_cromwell_mk_vii"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"np_comet_a34"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("ZB37")
	}
}
{"np_churchill_mk_vii"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"np_cromwell_mk_i"
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"np_churchill_mk_ii"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_churchill_mk_iv"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"np_churchill_gun_carrier"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
	}
}
{"np_valentine_mkiii" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_valentine_mkix" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
	{on fire "gun" overload
		{view start "flashbarrel1"}
		{view start "flashbarrel1smoke"}
		{ani_play "fire"}
		{ani_play "fire_gun"}
	}
}
{"np_valentine_mkxi" 
	("valentine_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
	{on fire "gun" overload
		{view start "flashbarrel1"}
		{view start "flashbarrel1smoke"}
		{ani_play "fire"}
		{ani_play "fire_gun"}
	}
}
{"np_matilda_mkii" 
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_matilda_mkii_cs" 
	("cromwell_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("ZB37")
	}
}
{"np_crusader_aa1 tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Autocannon_s2")
		{link_sound "action_recoil_Cannon"	"weapon/shot/cannon/s1/recoil/Shared/Autocannon_20to30mm/"}
	}
}
{"np_churchill_crocodile"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
	{on spawn
		{add_view "flamer_fire_tank" "flame" "foresight4"}
		{add_view "flamer_fire_barrel" "fire" "foresight4"}
	}
	{on operatable on
		{view start "fire"}
	}
	{on operatable off
		{view stop "fire"}
	}
	{on "_explosion"
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	("flame_weapon" args flamer1 60 4 40)
}
{"np_crusader_mki tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_crusader_mkii tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_crusader_mki_cs tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("ZB37")
	}
}
{"np_m30kangaroo tank"
	("m3lee_sound")
	{on "add_weapon_sound" overload
		("M2HB")
	}
}
{"np_mk2daimler tank"
	("daimler_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_staghound_mk3 tank" 
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"np_aec_mk2"
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"np_aec_mk3"
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"np_black_prince" 
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("ZB37")
	}
}
{"np_churchill_mk_viii"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
}
{"np_humber_mk4"
	("dingo_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("M1919A4")
	}
}
{"np_tetrarch_mk7"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"np_bishop"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_105to130mm_LV")
	}
}
{"np_universal_carrier tank"
	("universal_carrier_sound")
}
{"np_churchill_mk_ix"
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("ZB37")
	}
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"np_tog2" 
	("churchill_tank_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_HV")
		("ZB37")
	}
}
{"np_universal_mg_carrier tank"
	("universal_carrier_sound")
	{on "add_weapon_sound" overload
		("Vickers_MG")
	}
}
{"np_universal_boyes_carrier tank"
	("universal_carrier_sound")
	{on "add_weapon_sound" overload
		("ZB37")
	}
	
}
{"np_universal_mortar_carrier tank"
	("universal_carrier_sound")
	{on "add_weapon_sound" overload
		("Mortar_8cm")
	}
}
{"np_m4a1 tank"
	("m4_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm")
		("M1919A4")
	}
}
{"np_aec_aa"
	{on spawn
		{add_view "smoke_zenit"						"zenite_smoke00"			"shooter00"}
		{add_view "tank_canon_fire_20_25_auto"		"flashbarrelzenite00"		"shooter00"}
		{add_view "smoke_zenit"						"zenite_smoke01"			"shooter01"}
		{add_view "tank_canon_fire_20_25_auto"		"flashbarrelzenite01"		"shooter01"}
		{add_view "tank_fire_zenite_dust_ground"	"zenite_ground_fx"		"basis"}
		{add_view "tank_fire_zenite_dust_sand"		"zenite_sand_fx"		"basis"}
		{add_view "tank_fire_zenite_dust_snow"		"zenite_snow_fx"		"basis"}
	}
	("m8grayhound_sound")
	{on "add_weapon_sound" overload
		("M2HB_M33_Mount")
	}
	{on fire "gun" overload
		{if  name "00"
			{ani_play "fire01"}
			{view start "flashbarrelzenite00"}
			{view start "zenite_smoke00"}
			{delay 0.5
				{view pause "flashbarrelzenite00"}
			}
			{delay 5
				{view pause "zenite_smoke00"}
			}
		else name "01"
			{ani_play "fire02"}
			{view start "flashbarrelzenite01"}
			{view start "zenite_smoke01"}
			{delay 0.5
				{view pause "flashbarrelzenite01"}
			}
			{delay 5
				{view pause "zenite_smoke01"}
			}
		}
	}
}
;/*=========== British Vehicles End ===========*/

{"crusader_fr tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_50to57mm_HV")
		("ZB37")
	}
}
{"crusader_mk2_fr tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_37to40mm")
		("ZB37")
	}
}
{"crusader_mk2_cs_fr tank"
	("crusader_sound")
	{on "add_weapon_sound" overload
		("Cannon_75to76mm_LV")
		("ZB37")
	}
}